spring:
  datasource:
    url: jdbc:postgresql://db:5432/bigpaws
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

upload:
  path: /app/uploads

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
