spring:
  application:
    name: bigpaws-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/bigpaws
    driver-class-name: org.postgresql.Driver
    username: keonjo
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

upload:
  path: ./uploads

jwt:
  secret: YmlncGF3cy1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tMjAyNg==
  expiration: 86400000